//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forms
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FormDetail()
        {
            this.ValueDetails = new HashSet<ValueDetail>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid FormId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Title { get; set; }
        public System.Guid FormDetailsTypeId { get; set; }
        public Nullable<System.Guid> FormDetailsOptionId { get; set; }
        public string UserId { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public System.DateTime ModifiedDateTime { get; set; }
        public bool IsRequired { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual FormDetailsType FormDetailsType { get; set; }
        public virtual FormDetailsOption FormDetailsOption { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ValueDetail> ValueDetails { get; set; }
        public virtual Form Form { get; set; }
    }
}
